SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM BOOK_SALES AS S ,BOOK AS B, AUTHOR AS A 
WHERE SALES_DATE LIKE '2022-01%' AND B.BOOK_ID = S.BOOK_ID AND B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY B.AUTHOR_ID, CATEGORY 
ORDER BY AUTHOR_ID ASC, CATEGORY DESC