-- 코드를 입력하세요
SELECT  YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH , GENDER, COUNT(DISTINCT O.USER_ID) AS USERS
FROM USER_INFO U , ONLINE_SALE O 
WHERE U.USER_ID = O.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER HAVING(GENDER IS NOT NULL)
ORDER BY YEAR(SALES_DATE) ASC , MONTH(SALES_DATE) ASC, GENDER ASC