-- 코드를 입력하세요
SELECT  APNT_NO, PT_NAME, APPOINTMENT.PT_NO, APPOINTMENT.MCDP_CD,DR_NAME,APNT_YMD
FROM APPOINTMENT, PATIENT, DOCTOR
WHERE PATIENT.PT_NO = APPOINTMENT.PT_NO AND DOCTOR.DR_ID = APPOINTMENT.MDDR_ID
AND APPOINTMENT.MCDP_CD = 'CS' AND APNT_YMD LIKE "2022-04-13%" AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD ASC